version: "3.8"

services:
  scraper:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=recipe_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_SSL=false
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    depends_on:
      db:
        condition: service_healthy
    networks:
      - recipe-network
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=recipe_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - recipe-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  recipe-network:
    driver: bridge
