version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=recipe_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    command: npm start

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=recipe_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
