services:
  - type: worker
    name: recipe-scraper
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: recipe-db
          property: connectionString

databases:
  - name: recipe-db
    plan: free
    ipAllowList: []
